### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by Hoffenbar** [khchen/wNim#92] opened 2021-08-05 15:46 UTC
C:\WINDOWS\system32>nimble install wNim
Downloading https://github.com/khchen/wNim using git
  Verifying dependencies for wnim@0.13.0
      Info: Dependency on winim@>= 3.6.0 already satisfied
  Verifying dependencies for winim@3.6.1
 Installing npeg@>= 0.24.1
Downloading https://github.com/zevv/npeg using git
  Verifying dependencies for npeg@0.24.1
 Installing npeg@0.24.1
   Success: npeg installed successfully.
 Installing memlib@>= 1.1.0
    Prompt: memlib not found in any local packages.json, check internet for updated packages? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
       Tip: 31 messages have been suppressed, use --verbose to show them.
     Error: Package not found.

Ok, 2nd try works:

C:\WINDOWS\system32>nimble install wNim
Downloading https://github.com/khchen/wNim using git
  Verifying dependencies for wnim@0.13.0
      Info: Dependency on winim@>= 3.6.0 already satisfied
  Verifying dependencies for winim@3.6.1
      Info: Dependency on npeg@>= 0.24.1 already satisfied
  Verifying dependencies for npeg@0.24.1
 Installing memlib@>= 1.1.0
Downloading https://github.com/khchen/memlib using git
  Verifying dependencies for memlib@1.1.0
      Info: Dependency on winim@>= 3.6.0 already satisfied
  Verifying dependencies for winim@3.6.1
 Installing minhook@>= 1.0.0
Downloading https://github.com/khchen/minhook using git
  Verifying dependencies for minhook@1.0.0
 Installing minhook@1.0.0
   Success: minhook installed successfully.
 Installing memlib@1.1.0
   Success: memlib installed successfully.
 Installing wnim@0.13.0
   Success: wnim installed successfully.

So it's more a thing with nimble install then wnim I think....

**Comment by khchen** [comment] 2021-08-06 12:19
I cannot reproduce the error. And you are right, it seems a bug of nimble.
Maybe you can raise a issue at https://github.com/nim-lang/nimble.
Closing this...

**Closed by khchen** 2021-08-06 12:19 UTC
