### ISSUE TITLE
[Help] wFileDialog returns an empty sequence when using wFdMultiple.

### ISSUE THREAD

**Issue by Aetopia** [khchen/wNim#111] opened 2022-10-16 18:17 UTC
```nim
import wNim/wFileDialog
var fd = FileDialog(style=wFdOpen or wFdMultiple or wFdFileMustExist)
echo fd.display()
```
Using this code snippet simply returns an empy sequence when selecting multiple files.

I am not sure if this some issue with wNim or the parameters, I have passed to the `FileDialog` function.

**Comment by khchen** [comment] 2022-10-16 22:01
Thanks for report. After testing, this is a regression bug of strutils since nim 1.6.0. Nim 1.4.7 works correctly.
This code leads the problem:

```nim
import strutils
echo "abc\0\0\0".find("\0\0")
```

Nim 1.4.3 output 3.
Nim 1.6.0 output 0.

**Comment by Aetopia** [comment] 2022-10-17 03:50
Oh, thank you!

**Comment by khchen** [comment] 2022-10-17 07:30
Bug is in strutils. wNim won't be fixed.

**Closed** 2023-06-11 14:22 UTC
