### ISSUE TITLE
error: lvalue required as unary '&' operand

### ISSUE THREAD

**Issue by mbenam** [khchen/wNim#86] opened 2021-05-09 14:51 UTC
Hello,

I am trying out the examples. In every case I am getting the following error multiple times throughout the compilation. After searching, it seems to be an issue related to the c++ file generated. Thank you.

C:\Users\menam\nimcache\printpreview_d\@m..@s..@s..@s.nimble@spkgs@swnim-0.11.2@swNim@sprivate@swHelper.nim.c:1624:11: error: lvalue required as unary '&' operand
    T18_ = &((&bitmapInfo));
           ^

**Comment by khchen** [comment] 2021-05-22 10:08
Cannot reproduce.
What is your environment?

**Comment by khchen** [comment] 2021-08-06 12:22
Fixed in winim.

**Closed by khchen** 2021-08-06 12:22 UTC
